### PR TITLE
ps2 ee port 

### PR DESCRIPTION
**Pull request by Wolf3s**
This pr superceeds #1
credits: @7dog123 for the first port.

### CODE REVIEW

**Comment by Wolf3s** [comment]
```cmake -S . -B build "-DCMAKE_TOOLCHAIN_FILE=${PS2DEV}/share/ps2dev.cmake" "-DCMAKE_INSTALL_PREFIX=${PS2SDK}/ports" -Denable=aufile=OFF -DBUILD_SHARED_LIBS=OFF -Denable-dbus=OFF -Denable-ipv6=OFF -Denable-jack=OFF -Denable-libinstpatch=OFF -Denable-libsndfile=OFF -Denable-midishare=OFF -Denable-network=ON -Denable-oss=OFF -Denable-dsound=OFF -Denable-wasapi=OFF -Denable-waveout=OFF -Denable-winmidi=OFF -Denable-sdl2=ON -Denable-pulseaudio=OFF -Denable-pipewire=OFF -Denable-readline=OFF -Denable-threads=ON -Denable-openmp=OFF```

**Comment by fjtrujy** [comment]
Can you please revert all the cosmetic changes and changes totally unrelated to the PS2 port? 
it will help us to keep track of all the specific required changes.

**Comment by Wolf3s** [comment]
> Can you please revert all the cosmetic changes and changes totally unrelated to the PS2 port? it will help us to keep track of all the specific required changes.

Well then, I should deprecate this one and use sed patch on ps2sdk-ports for achive that.

**Comment by fjtrujy** [comment]
I was fine with the port, but we should keep the changes as small as possible.
I have the impression that tons of the changes we have here can be skipt with some specific boolean flags.
I don't think that having a `sed` on `ps2sdk-ports` will make things easier to follow honestly

**Comment by Wolf3s** [comment]
> I was fine with the port, but we should keep the changes as small as possible. I have the impression that tons of the changes we have here can be skipt with some specific boolean flags. I don't think that having a `sed` on `ps2sdk-ports` will make things easier to follow honestly

Well it's only three stuff changed also there are some specific ones that needs to open a PR to remove inside like glib

**Pull request closed without merging**
